### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by PadowYT2**
**Merge when v2-pr13**
* v2-pr13
* Remove useless spaces (code formatting)
* Add missing semicolons
* Remove cheese command from `commands.json`
* Add MCPE info
* Changed NamelessMC Plugin URL
* Delete `discord-widget.json`

### CODE REVIEW

**Review by supercrafter100 — COMMENTED** [review]
I'm unsure what the point of #355dc2f is?

**Comment by PadowYT2** [comment]
> I'm unsure what the point of #355dc2f is? Why did you remove the discord-widget as well?

What #355dc2f? Because in pr13 the file was moved and I don't think people will get that error

**Comment by supercrafter100** [comment]
> What #355dc2f?

Was talking about the "non existing commits" commit

**Comment by PadowYT2** [comment]
> I'm unsure what the point of #355dc2f is? Why did you remove the discord-widget as well?

Oh, it came up and it was so annoying and I couldn't remove it

**Comment by PadowYT2** [comment]
I'll reopen the pr when pr13 is out

**Pull request closed without merging**
